"""
USB Bridge Protocol Definitions

Protocol for bridging USB hardware between Poseidon (Amiga) and libusb (host)
via the A314 communication layer.

All multi-byte fields use big-endian (network) byte order.
"""

# Message Types (first byte of MSG_DATA payload)
USB_ROOT_HUB_STATUS_REQ = 1
USB_ROOT_HUB_STATUS_RES = 2
USB_DEVICE_ATTACHED = 3
USB_DEVICE_DETACHED = 4
USB_CONTROL_TRANSFER_REQ = 5
USB_CONTROL_TRANSFER_RES = 6
USB_BULK_TRANSFER_REQ = 7
USB_BULK_TRANSFER_RES = 8
USB_INT_TRANSFER_REQ = 9
USB_INT_TRANSFER_RES = 10
USB_RESET_DEVICE_REQ = 11
USB_RESET_DEVICE_RES = 12
USB_ABORT_TRANSFER_REQ = 13
USB_ABORT_TRANSFER_RES = 14

# Transfer Status Codes
USB_STATUS_OK = 0
USB_STATUS_STALL = 1
USB_STATUS_NAK_TIMEOUT = 2
USB_STATUS_ERROR = 3

# Device Speed Codes
USB_SPEED_FULL = 0
USB_SPEED_LOW = 1
USB_SPEED_HIGH = 2

# Port Status Flags
USB_PORT_CONNECTION = 0x0001
USB_PORT_ENABLE = 0x0002
USB_PORT_SUSPEND = 0x0004
USB_PORT_OVER_CURRENT = 0x0008
USB_PORT_RESET = 0x0010
USB_PORT_POWER = 0x0100
USB_PORT_LOW_SPEED = 0x0200
USB_PORT_HIGH_SPEED = 0x0400

# Port Change Flags
USB_PORT_C_CONNECTION = 0x0001
USB_PORT_C_ENABLE = 0x0002
USB_PORT_C_SUSPEND = 0x0004
USB_PORT_C_OVER_CURRENT = 0x0008
USB_PORT_C_RESET = 0x0010
